### ISSUE TITLE
Update for image_processing.face_counter_XXXX fails

### ISSUE THREAD

**Issue by koldogut** [robmarkcole/HASS-Deepstack-face#25]
After upgrading to latest version of HA and Deepstack I'm starting to get this error:

`Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state await self.async_device_update() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update raise exc File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 132, in async_update await self.async_process_image(image.content) File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 112, in async_process_image return await self.hass.async_add_executor_job(self.process_image, image) File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/deepstack_face/image_processing.py", line 210, in process_image self._dsface.recognise(image) AttributeError: 'DeepstackFace' object has no attribute 'recognise'`

Versions as follows:

HA: 2020.12.1
Deep Stack (docker): Latest (Open source models version)
HASS DeepStack: v3.5

**Comment by koldogut** [comment]
Error persists in ver. 3.7
