### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Salvora** [robmarkcole/HASS-Deepstack-face#58]
I am getting below error when image processing face service is called. I had no such problem with object integration. The error indicates that the local language specific characters are not passed successfully. I do indeed use such character for naming on the source config. The \u0131 character is dotless "i" as per https://www.compart.com/en/unicode/U+0131.

```yaml
  source:
    - entity_id: camera.laxdiskstation_mutfak_kamera
      name: "Mutfak Kamera Yüz Tanıma (GS60)"
```

```
2021-10-22 02:07:50 ERROR (MainThread) [homeassistant.helpers.entity] Update for image_processing.mutfak_kamera_yuz_tanima_gs60 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/PIL/ImageDraw.py", line 414, in draw_text
    mask, offset = font.getmask2(
AttributeError: 'ImageFont' object has no attribute 'getmask2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 438, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 625, in async_device_update
    raise exc
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 138, in async_update
    await self.async_process_image(image.content)
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 118, in async_process_image
    return await self.hass.async_add_executor_job(self.process_image, image)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deepstack_face/image_processing.py", line 247, in process_image
    self.save_image(
  File "/config/custom_components/deepstack_face/image_processing.py", line 335, in save_image
    draw_box(
  File "/usr/src/homeassistant/homeassistant/util/pil.py", line 45, in draw_box
    draw.text(
  File "/usr/local/lib/python3.9/site-packages/PIL/ImageDraw.py", line 469, in text
    draw_text(ink)
  File "/usr/local/lib/python3.9/site-packages/PIL/ImageDraw.py", line 429, in draw_text
    mask = font.getmask(
  File "/usr/local/lib/python3.9/site-packages/PIL/ImageFont.py", line 149, in getmask
    return self.font.getmask(text, mode)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0131' in position 10: ordinal not in range(256) 
```

**Comment by robmarkcole** [comment]
sounds like something to raise with home assistant directly, afraid I cannot help
